// The transfer window, between seasons. Offers are generated by the same
// valuation the bots bid with, so this is a negotiation against the opponents
// you just faced — not a shop.

import { useMemo, useState } from "react";
import { motion } from "motion/react";
import { useGameStore } from "../store/gameStore";
import { applyTrade, generateOffers, tradeValue, type TradeOffer } from "../engine/trading";
import { newCareer } from "../engine/career";
import { seedRng } from "../engine/rng";
import { money } from "../components/format";
import Portrait from "../components/Portrait";

export default function TradeWindow({ onClose }: { onClose: () => void }) {
  const auction = useGameStore((s) => s.auction);
  const humanId = useGameStore((s) => s.humanId);
  const career = useGameStore((s) => s.career) ?? newCareer(humanId);
  const [done, setDone] = useState<string[]>([]);

  const me = auction.franchises.find((f) => f.id === humanId)!;
  const others = auction.franchises.filter((f) => f.id !== humanId);

  const offers = useMemo(
    () => generateOffers(me, others, career, seedRng(auction.rngSeed ^ 0x7bad))[0],
    [me, others, career, auction.rngSeed],
  );

  const accept = (offer: TradeOffer, key: string) => {
    useGameStore.setState({
      auction: { ...auction, franchises: applyTrade(auction.franchises, humanId, offer) },
    });
    setDone((d) => [...d, key]);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      onClick={onClose}
      className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-950/90 p-4 backdrop-blur-sm"
    >
      <motion.div
        initial={{ scale: 0.96, y: 16 }} animate={{ scale: 1, y: 0 }}
        onClick={(e) => e.stopPropagation()}
        className="my-6 w-full max-w-2xl rounded-2xl border border-slate-700 bg-slate-900 p-5"
      >
        <div className="flex items-start">
          <div>
            <h3 className="text-xl font-black">Transfer window</h3>
            <p className="mt-0.5 text-xs text-slate-400">
              Offers from rival franchises for players they rate more than you do.
            </p>
          </div>
          <span className="ml-auto rounded bg-slate-800 px-2 py-1 font-mono text-xs font-bold text-amber-400">
            {money(me.budget)}
          </span>
          <button onClick={onClose} className="ml-2 rounded bg-slate-800 px-2 py-1 text-sm hover:bg-slate-700">
            ✕
          </button>
        </div>

        {offers.length === 0 && (
          <p className="mt-6 text-center text-sm italic text-slate-500">
            Nobody wants anything you have. Flattering, in a way.
          </p>
        )}

        <ul className="mt-4 space-y-2">
          {offers.map((o, i) => {
            const key = `${o.partnerId}-${o.give.id}-${o.receive?.id ?? "cash"}`;
            const partner = auction.franchises.find((f) => f.id === o.partnerId)!;
            const gained = o.cash + (o.receive ? tradeValue(o.receive, me, career) : 0);
            const lost = tradeValue(o.give, me, career);
            const good = gained > lost;
            const taken = done.includes(key);
            return (
              <li
                key={key + i}
                className={`rounded-xl p-3 ${taken ? "bg-slate-900/40 opacity-50" : "bg-slate-950/60"}`}
              >
                <p className="text-[10px] font-black uppercase tracking-widest" style={{ color: partner.color }}>
                  {partner.name}
                </p>
                <div className="mt-1.5 flex flex-wrap items-center gap-3 text-sm">
                  <span className="flex items-center gap-1.5">
                    <Portrait player={o.give} size={26} />
                    <span className="text-red-300">− {o.give.name}</span>
                  </span>
                  {o.receive && (
                    <span className="flex items-center gap-1.5">
                      <Portrait player={o.receive} size={26} />
                      <span className="text-emerald-300">+ {o.receive.name}</span>
                    </span>
                  )}
                  {o.cash !== 0 && (
                    <span className={o.cash > 0 ? "font-mono text-emerald-300" : "font-mono text-red-300"}>
                      {o.cash > 0 ? "+" : "−"}{money(Math.abs(o.cash))}
                    </span>
                  )}
                  <span className={`ml-auto text-[10px] font-bold uppercase ${good ? "text-emerald-400" : "text-slate-500"}`}>
                    {good ? "good value" : "they win this one"}
                  </span>
                  <button
                    disabled={taken}
                    onClick={() => accept(o, key)}
                    className="rounded-lg bg-amber-500 px-3 py-1.5 text-xs font-black text-slate-950 enabled:hover:bg-amber-400 disabled:opacity-40"
                  >
                    {taken ? "Done" : "Accept"}
                  </button>
                </div>
              </li>
            );
          })}
        </ul>
      </motion.div>
    </motion.div>
  );
}
