// Between-season transfer window. Squads are illiquid after an auction —
// you own who you bought — and a trade window is the pressure valve: sell a
// luxury you can't fit, or buy the bowler you failed to land.
//
// Bots value players with the same brain that bids for them, so a trade is a
// negotiation against the same opponent you just faced at the auction.

import type { Career } from "./career";
import type { Franchise, Player } from "./types";
import { effectiveRating } from "./career";
import { ratingValue } from "./bots";
import { unfilledNeeds, OVERSEAS_MAX, SQUAD_MAX, roleCount } from "./rules";
import { nextFloat, type Rng } from "./rng";

export interface TradeOffer {
  /** Player leaving the human's squad. */
  give: Player;
  /** Player coming the other way, or null for a straight cash sale. */
  receive: Player | null;
  /** Cash to the human. Negative means the human pays. */
  cash: number;
  partnerId: string;
}

/** What a franchise thinks a player is worth, in lakhs. */
export function tradeValue(player: Player, franchise: Franchise, career: Career): number {
  const rating = effectiveRating(player, career);
  let value = ratingValue(rating);

  // A player who fills a hole is worth more; a fourth keeper is worth less.
  const needs = unfilledNeeds(franchise.squad);
  if ((needs[player.role] ?? 0) > 0) value *= 1.35;
  const typical: Record<string, number> = { BAT: 4, BOWL: 5, AR: 3, WK: 2 };
  if (roleCount(franchise.squad, player.role) >= (typical[player.role] ?? 3)) value *= 0.6;

  return Math.round(value);
}

export interface TradeCheck {
  ok: boolean;
  reason?: string;
}

/** Would this trade leave either squad legal? */
export function canTrade(
  human: Franchise,
  partner: Franchise,
  offer: TradeOffer,
): TradeCheck {
  const humanAfter = [
    ...human.squad.filter((p) => p.id !== offer.give.id),
    ...(offer.receive ? [offer.receive] : []),
  ];
  const partnerAfter = [
    ...partner.squad.filter((p) => p.id !== offer.receive?.id),
    offer.give,
  ];

  if (humanAfter.length > SQUAD_MAX || partnerAfter.length > SQUAD_MAX) {
    return { ok: false, reason: "squad would be over the limit" };
  }
  const os = (squad: Player[]) => squad.filter((p) => p.overseas).length;
  if (os(humanAfter) > OVERSEAS_MAX || os(partnerAfter) > OVERSEAS_MAX) {
    return { ok: false, reason: "overseas limit" };
  }
  if (human.budget + offer.cash < 0) return { ok: false, reason: "you can't afford it" };
  if (partner.budget - offer.cash < 0) return { ok: false, reason: "they can't afford it" };
  return { ok: true };
}

/**
 * Offers the other franchises would actually accept — generated by valuing
 * every plausible swap from both sides and keeping the ones where the partner
 * comes out ahead on their own valuation.
 */
export function generateOffers(
  human: Franchise,
  others: Franchise[],
  career: Career,
  rng: Rng,
  limit = 6,
): [TradeOffer[], Rng] {
  let r = rng;
  const offers: TradeOffer[] = [];

  for (const partner of others) {
    for (const give of human.squad) {
      const theirValue = tradeValue(give, partner, career);
      const myValue = tradeValue(give, human, career);
      // They only bite if they want the player more than you do.
      if (theirValue < myValue * 1.05) continue;

      // Straight sale for cash.
      const [roll, next] = nextFloat(r);
      r = next;
      const cash = Math.round(theirValue * (0.85 + roll * 0.25));
      const sale: TradeOffer = { give, receive: null, cash, partnerId: partner.id };
      // Every generated offer must be legal for BOTH squads — otherwise the
      // UI would happily present a trade that breaches the overseas cap.
      if (canTrade(human, partner, sale).ok) offers.push(sale);

      // Or a swap for someone they can spare.
      const spare = partner.squad
        .filter((p) => tradeValue(p, partner, career) < theirValue)
        .sort((a, b) => tradeValue(b, human, career) - tradeValue(a, human, career))[0];
      if (spare) {
        const diff = theirValue - tradeValue(spare, partner, career);
        const swap: TradeOffer = {
          give, receive: spare, cash: Math.round(diff * 0.6), partnerId: partner.id,
        };
        if (canTrade(human, partner, swap).ok) offers.push(swap);
      }
    }
  }

  // Best for the human first: what you gain in cash plus incoming value.
  offers.sort(
    (a, b) =>
      b.cash + (b.receive ? tradeValue(b.receive, human, career) : 0) -
      (a.cash + (a.receive ? tradeValue(a.receive, human, career) : 0)),
  );
  return [offers.slice(0, limit), r];
}

/** Execute a trade, returning updated franchises. */
export function applyTrade(
  franchises: Franchise[],
  humanId: string,
  offer: TradeOffer,
): Franchise[] {
  return franchises.map((f) => {
    if (f.id === humanId) {
      return {
        ...f,
        budget: f.budget + offer.cash,
        squad: [
          ...f.squad.filter((p) => p.id !== offer.give.id),
          ...(offer.receive ? [offer.receive] : []),
        ],
      };
    }
    if (f.id === offer.partnerId) {
      return {
        ...f,
        budget: f.budget - offer.cash,
        squad: [
          ...f.squad.filter((p) => p.id !== offer.receive?.id),
          offer.give,
        ],
      };
    }
    return f;
  });
}
